# 应用配置
spring:
  application:
    name: RiskLendPro
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 安全配置
  security:
    user:
      name: admin
      password: admin

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api/v1

# MyBatis-Plus配置（使用@Select注解，无需XML）
mybatis-plus:
  type-aliases-package: org.example.risklendpro.user.entity,org.example.risklendpro.loan.entity,org.example.risklendpro.risk.entity,org.example.risklendpro.risk.credit
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id

# 日志配置
logging:
  level:
    root: info
    org.example.risklendpro: debug

risk:
  coze:
    token: pat_JbXEzhPyB3jDRjS8d4WJa3C3jcYphuyyO1Hp9y250t5D0gysF5GHHHSRN6JZer07
